_target_: src.explainability.explain_utils.integratedgradients
_partial_: true

color_map: 
  _target_: matplotlib.colors.LinearSegmentedColormap.from_list
  name: "custom blue" 
  N: 256
  colors: [[0, "#ffffff"], [0.25, "#000000"], [1, "#000000"]] 
  