# @package _global_

# to execute this experiment run:
# python explainability.py experiment=model_explainability.yaml

defaults:
  - _self_
  - model: timm.yaml
  - explainability: integratedgradients.yaml

IMAGENET_DEFAULT_MEAN : (0.485, 0.456, 0.406)
IMAGENET_DEFAULT_STD : (0.229, 0.224, 0.225)

imput_im_size : 224
image_path : ??

model:
  net:
    model_name: resnet18
